### ISSUE TITLE
Add Holes Into Polygons

### ISSUE THREAD

**Issue by frastlin** [alexbol99/flatten-js#24]
It would be very useful to specify a whole in a polygon using either a new method, such as addHole, or the addFace method. The [area method states:](https://alexbol99.github.io/flatten-js/Polygon.html) "Returns area of the polygon. Area of an island will be added, area of a hole will be subtracted"

So it looks as if holes were contemplated at one point in time.

**Comment by alexbol99** [comment]
Hi @frastlin 

Of cause polygon in this library supports holes.

In order to be displayed as a hole, face should be simply placed inside another face - "island".

But if you want to distinguish between islands and holes in algorithms, like area measurement, inclusion check or boolean operations, **islands and holes should have opposite orientations**: for instance, if islands are oriented clockwise (```Flatten.ORIENTATION.CW```), holes have to be oriented counter clockwise (```Flatten.ORIENTATION.CCW```).

If you are not sure which orientation the face has, use this code to detect and, if need, revert orientation:
```
let face = polygon.addFace(points.map(([x, y]) => new Point(x, y)));
 if (face.orientation() !== Flatten.ORIENTATION.CCW) {
    face.reverse();
 }
```
Note, that when orientation calculated, axe Y is considered to direction from down up, like in math.

Best regards,
Alex Bol

**Comment by frastlin** [comment]
OK, I can't seem to make this work with the contains(point) or distanceTo algorithm. if I do a distanceTo algorithm in the middle of a hole, it should give me the distance to the nearest points, and if I do a check in the hole, I would expect it not to say I'm in a polygon.

**Comment by alexbol99** [comment]
Can you send me your data?

**Comment by frastlin** [comment]
I figured it out, my points were not correct. If you do the counterclockwise for the hole and clockwise for everything else, that works perfectly.
