### ISSUE TITLE
Bug in Polygon.contain method when used on segments 

### ISSUE THREAD

**Issue by bernizt** [alexbol99/flatten-js#31]
- I'm trying to use the method **contain** of a **polygon** to check if a **segment** is inside it.
- The results are not always correct. Check the [runkit example](https://runkit.com/bernizt/polygon-contain-bug) for a correct detection and a wrong detection.
- Note: changing the tolerance parameter doesn't make a difference.

**Comment by alexbol99** [comment]
Hello @bernizt ,
Sorry for the late reply.
I tried your example in the latest release (1.2.1) and got expected result in both cases.
See this notebook: https://observablehq.com/d/d407b9bed460e39b
Thanks,
Alex

**Comment by karolis-k** [comment]
I think there is still a bug. I updated the example, just changed the shape of polygon a little: https://github.com/alexbol99/flatten-js/issues/31
I quickly checked the code and it seems that the problem is that segment's/edge's inclusion is checked only by start, end and middle points. In previous example it just happened so by coincidence that middle point was outside polygon.

**Comment by alexbol99** [comment]
You are right, this method was incomplete. Try new release v1.2.6, problem should be fixed.
