### ISSUE TITLE
Can you please explain why norm of Line is 90 CCW from it vector?

### ISSUE THREAD

**Issue by redexp** [alexbol99/flatten-js#40]
Hello, I'm trying to figure out why `Flatten.Line` has `norm` vector which is 90 CCW from original vector? It was surprise for me that to build vertical line code should be NOT 
```javascript
new Line(new Point(10, 10), new Vector(0, 1))
```
it should be 
```javascript 
new Line(new Point(10, 10), new Vector(-1, 0))
``` 
instead. In docs it says just `norm - normal vector to a line`, nothing about 90 CCW.

Thanks great lib.

**Comment by alexbol99** [comment]
Hello, @redexp Sergii

I don't understand what do you mean by "original vector", but both options are valid.
Both options give same vertical line that passes through the point (10,10)
What kind of problem you have with this definition?

Best regards,
Alex

**Comment by redexp** [comment]
@alexbol99 as for me, first one should be vertical line, but it is horizontal line. To build vertical line I need to pass horizontal vector,  why?

**Comment by redexp** [comment]
This is vertical vector `new Vector(0, 1)` right? and with it we should build vertical line like this `new Line(new Point(10, 10), new Vector(0, 1))`, right?

**Comment by alexbol99** [comment]
My answer was quick and incomplete.
Constructing of the line with normal vector (n) and point (pt0) means definition of the line equation in vector form :
```
 n * p = 0
```
where 
**norm** - normal (ortogonal) vector to a line
**p = pt - pt0** - vector from a point p0 that line passes through to an arbitrary point on a line
and **'*''** is a scalar product

So, in order to construct vertical line you need to create horizontal vector, and both 
```javascript
new Line(new Point(10, 10), new Vector(-1, 0))
```
and
```javascript
new Line(new Point(10, 10), new Vector(1, 0))
```
are constructors for same vertical line.

You also have an option to construct line that pass through two points, like this:
```javascript
new Line(new Point(10, 10), new Point(10,20))
```

**Comment by redexp** [comment]
Thank you for explanation
