### ISSUE TITLE
Zero division

### ISSUE THREAD

**Issue by doox911** [alexbol99/flatten-js#59]
```
  let shapes = [
    point(0, 0), point(200, 0),
    point(200, 0), point(200, 200),
    point(200, 200), point(0, 200),
    point(0, 200), point(0, 0),
  ];

  let polygon = new Polygon();
  polygon.addFace(shapes);
  let offsetPolygon = offset(polygon, 2);
```
I get an error:

```
Error: Zero division
    at Function.get ZERO_DIVISION [as ZERO_DIVISION]
    at Vector.normalize 
    at offsetSegment 
    at offset 
```
What am I doing wrong? And How do I create a simple square by points?

**Comment by alexbol99** [comment]
Hello @doox911 ,

When you define polygon, you may do it in two ways:
* define using array of points as vertices, each vertex only one time:
```javascript
let shapes = [
        point(0, 0), point(200, 0), point(200, 200), point(0, 200)
 ]
```
* or define using array of shapes, segments in this case:
```javascript
let shapes = [
            segment(point(0, 0), point(200, 0)),
            segment(point(200, 0), point(200, 200)),
            segment(point(200, 200), point(0, 200)),
            segment(point(0, 200), point(0, 0))
];
```

Next thing, orientation of the polygon is important.
Current version supports only polygons oriented clockwise (with respect to axe y goes up, like in math).
Polygon defined by points in your example oriented counter clockwise.

In order to get proper result you need to reverse orientation:
```javascript
let polygon = new Polygon(shapes);
polygon.reverse();                               // reverse orientation
```

In the future version I will add support of polygons in any orientation
